"""mastering.py — High-precision audio mastering and concatenation using PCM WAV intermediates."""
import subprocess
import logging
import os
import tempfile
import uuid
from pathlib import Path

log = logging.getLogger(__name__)

# Broadcast EQ and standard podcast loudness (EBU R128)
WARMTH_FILTER = "highpass=f=75,equalizer=f=280:t=q:w=1.2:g=1.5,equalizer=f=3400:t=q:w=1.5:g=1.0"
LOUDNORM = "loudnorm=I=-16:TP=-1.5:LRA=11"


def _ffmpeg(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "warning", *args]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"ffmpeg error:\n{result.stderr[-800:]}")
    return result


def _get_duration_seconds(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def _make_silence_wav(duration_ms: int, out_path: Path):
    """Generate bit-exact PCM WAV silence of specific duration."""
    duration_s = max(duration_ms / 1000.0, 0.05)
    _ffmpeg(
        "-f", "lavfi",
        "-i", "anullsrc=r=44100:cl=stereo",
        "-t", f"{duration_s:.3f}",
        "-c:a", "pcm_s16le",
        str(out_path),
    )


def _trim_to_wav(src: Path, dst: Path):
    """
    1. Strip leading and trailing silence generated by Edge-TTS.
    2. Convert to uncompressed 44.1kHz 16-bit PCM Stereo WAV (zero codec delay/priming).
    """
    trim_filter = (
        "silenceremove=start_periods=1:start_duration=0.01:start_threshold=-45dB,"
        "areverse,"
        "silenceremove=start_periods=1:start_duration=0.01:start_threshold=-45dB,"
        "areverse,"
        "aformat=sample_fmts=s16:sample_rates=44100:channel_layouts=stereo"
    )
    _ffmpeg(
        "-i", str(src),
        "-af", trim_filter,
        "-c:a", "pcm_s16le",
        str(dst),
    )


def _concat_files(file_list: list[Path], out_path: Path):
    """Concatenate audio files using FFmpeg concat demuxer (helper for tests and pipelines)."""
    if not file_list:
        raise RuntimeError("Empty file list for concat")
    list_content = "\n".join(f"file '{f.resolve()}'" for f in file_list)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False, encoding="utf-8") as f:
        f.write(list_content)
        list_file = f.name
    try:
        _ffmpeg("-f", "concat", "-safe", "0", "-i", list_file, "-c:a", "pcm_s16le", str(out_path))
    finally:
        try:
            os.unlink(list_file)
        except OSError:
            pass


def _determine_gap_ms(curr_seg: dict | None, next_seg: dict | None) -> int:
    """Calculate tight, realistic human conversational pauses."""
    if not curr_seg or not next_seg:
        return 200

    curr_text = curr_seg.get("text", "").strip()
    next_text = next_seg.get("text", "").strip()
    next_words = len(next_text.split())

    # Quick reaction / interjection ("Right.", "Wait, what?") -> near instant
    if next_words <= 4:
        return 100

    # Responding to a direct question -> crisp reaction
    if curr_text.endswith("?"):
        return 180

    # Same speaker continuing thought
    if curr_seg.get("speaker") == next_seg.get("speaker"):
        return 140

    # Standard conversation exchange
    return 220


def master(
    segment_files: list[Path],
    output_path: Path,
    assets_dir: Path | None = None,
    dialog: list[dict] | None = None,
) -> Path:
    """
    Master dialogue segments into a broadcast-ready MP3 podcast episode:
    1. Trims edge-tts silence padding into lossless PCM WAV.
    2. Inserts tight natural human pauses (100ms - 220ms).
    3. Concatenates losslessly in PCM domain.
    4. Applies broadcast EQ and EBU R128 two-pass loudnorm to 128kbps CBR MP3.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_dir = output_path.parent / f"_mastering_tmp_{uuid.uuid4().hex[:8]}"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    try:
        # Step 1: Pre-process each segment to clean WAV
        log.info(f"Trimming padding across {len(segment_files)} segments to clean PCM WAV...")
        wav_segs: list[Path] = []
        for i, seg_path in enumerate(segment_files):
            wav_path = tmp_dir / f"clean_{i:04d}.wav"
            try:
                _trim_to_wav(seg_path, wav_path)
                wav_segs.append(wav_path)
            except Exception as e:
                log.warning(f"Failed to trim segment {i}, fallback converting raw: {e}")
                # Fallback format conversion without silenceremove
                _ffmpeg("-i", str(seg_path), "-aformat", "sample_fmts=s16:sample_rates=44100:channel_layouts=stereo", "-c:a", "pcm_s16le", str(wav_path))
                wav_segs.append(wav_path)

        # Step 2: Prepare silence WAVs
        gap_cache: dict[int, Path] = {}

        def get_gap_wav(ms: int) -> Path:
            if ms not in gap_cache:
                p = tmp_dir / f"gap_{ms}ms.wav"
                _make_silence_wav(ms, p)
                gap_cache[ms] = p
            return gap_cache[ms]

        # Step 3: Build ordered sequence
        ordered: list[Path] = []

        intro = (assets_dir / "intro.mp3") if assets_dir else None
        outro = (assets_dir / "outro.mp3") if assets_dir else None

        if intro and intro.exists():
            intro_wav = tmp_dir / "intro.wav"
            _ffmpeg("-i", str(intro), "-aformat", "sample_fmts=s16:sample_rates=44100:channel_layouts=stereo", "-c:a", "pcm_s16le", str(intro_wav))
            ordered.append(intro_wav)
            ordered.append(get_gap_wav(250))
            log.info("Intro jingle included.")

        for i, seg in enumerate(wav_segs):
            ordered.append(seg)
            if i < len(wav_segs) - 1:
                curr_d = dialog[i] if (dialog and i < len(dialog)) else None
                next_d = dialog[i + 1] if (dialog and i + 1 < len(dialog)) else None
                gap_ms = _determine_gap_ms(curr_d, next_d)
                ordered.append(get_gap_wav(gap_ms))

        if outro and outro.exists():
            outro_wav = tmp_dir / "outro.wav"
            _ffmpeg("-i", str(outro), "-aformat", "sample_fmts=s16:sample_rates=44100:channel_layouts=stereo", "-c:a", "pcm_s16le", str(outro_wav))
            ordered.append(get_gap_wav(250))
            ordered.append(outro_wav)
            log.info("Outro jingle included.")

        # Step 4: Concat all WAVs losslessly in PCM domain
        raw_wav = tmp_dir / "raw_concat.wav"
        list_content = "\n".join(f"file '{f.resolve()}'" for f in ordered)
        list_file = tmp_dir / "concat_list.txt"
        list_file.write_text(list_content, encoding="utf-8")

        log.info(f"Concatenating {len(ordered)} PCM elements...")
        _ffmpeg("-f", "concat", "-safe", "0", "-i", str(list_file), "-c:a", "pcm_s16le", str(raw_wav))

        # Step 5: Broadcast Warmth EQ & EBU R128 two-pass loudnorm directly to final MP3
        log.info("Applying broadcast EQ & EBU R128 loudnorm (pass 1: measure)...")
        pass1 = _ffmpeg(
            "-i", str(raw_wav),
            "-af", f"{WARMTH_FILTER},{LOUDNORM}:print_format=json",
            "-f", "null", "-",
            check=False,
        )

        import json, re
        measured = {}
        try:
            json_matches = re.findall(r'(\{[^{}]*"input_i"[^{}]*\})', pass1.stderr, re.DOTALL)
            if json_matches:
                measured = json.loads(json_matches[-1])
        except Exception as e:
            log.warning(f"Failed to parse loudnorm stats: {e}")

        log.info("Applying broadcast EQ & EBU R128 loudnorm (pass 2: render MP3)...")
        if measured.get("input_i") and measured.get("input_lra") and measured.get("input_tp"):
            loudnorm_filter = (
                f"{LOUDNORM}:"
                f"measured_I={measured['input_i']}:"
                f"measured_LRA={measured['input_lra']}:"
                f"measured_TP={measured['input_tp']}:"
                f"measured_thresh={measured.get('input_thresh', '-70')}:"
                f"offset={measured.get('target_offset', '0')}:"
                f"linear=true:print_format=none"
            )
        else:
            loudnorm_filter = LOUDNORM

        _ffmpeg(
            "-i", str(raw_wav),
            "-af", f"{WARMTH_FILTER},{loudnorm_filter}",
            "-ar", "44100",
            "-codec:a", "libmp3lame",
            "-b:a", "128k",
            str(output_path),
        )

        duration = _get_duration_seconds(output_path)
        size_mb = output_path.stat().st_size / 1024 / 1024
        log.info(f"Mastered: {output_path} | {duration:.1f}s | {size_mb:.2f} MB")
        return output_path

    finally:
        import shutil
        shutil.rmtree(tmp_dir, ignore_errors=True)
