"""mastering.py — Assemble, master, and export final podcast MP3 via FFmpeg."""
import subprocess
import logging
import os
import tempfile
import uuid
from pathlib import Path

log = logging.getLogger(__name__)

# Broadcast EQ and standard podcast loudness (EBU R128)
WARMTH_FILTER = "highpass=f=75,equalizer=f=280:t=q:w=1.2:g=1.5,equalizer=f=3400:t=q:w=1.5:g=1.0"
LOUDNORM = "loudnorm=I=-16:TP=-1.5:LRA=11"


def _ffmpeg(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "warning", *args]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"ffmpeg error:\n{result.stderr[-800:]}")
    return result


def _get_duration_seconds(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, check=True,
    )
    return float(result.stdout.strip())


def _make_room_tone(duration_ms: int, out_path: Path):
    """Generate subtle pink noise room tone (-62dB) instead of jarring digital dead air."""
    duration_s = max(duration_ms / 1000.0, 0.05)
    _ffmpeg(
        "-f", "lavfi",
        "-i", "anoisesrc=c=pink:r=44100:a=0.0006",
        "-t", f"{duration_s:.3f}",
        "-codec:a", "libmp3lame",
        "-b:a", "128k",
        str(out_path),
    )


def _clean_and_pan_segment(src: Path, dst: Path, speaker: str):
    """
    1. Strip leading and trailing silence generated by Edge-TTS.
    2. Apply micro-fades (10ms) to eliminate audio clicks.
    3. Pan speaker slightly in stereo field (Alex 12% Left, Sam 12% Right) for spatial realism.
    """
    trim_filter = (
        "silenceremove=start_periods=1:start_duration=0.01:start_threshold=-45dB,"
        "areverse,"
        "silenceremove=start_periods=1:start_duration=0.01:start_threshold=-45dB,"
        "areverse,"
        "afade=t=in:d=0.01,afade=t=out:d=0.015"
    )

    if speaker == "Alex":
        pan_filter = "pan=stereo|c0=0.88*c0+0.12*c1|c1=0.12*c0+0.88*c1"
    else:  # Sam
        pan_filter = "pan=stereo|c0=0.12*c0+0.88*c1|c1=0.88*c0+0.12*c1"

    _ffmpeg(
        "-i", str(src),
        "-af", f"{trim_filter},{pan_filter}",
        "-codec:a", "libmp3lame",
        "-b:a", "192k",
        str(dst),
    )


def _concat_files(file_list: list[Path], out_path: Path):
    """Concatenate audio files using FFmpeg concat demuxer."""
    list_content = "\n".join(f"file '{f.resolve()}'" for f in file_list)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False, encoding="utf-8") as f:
        f.write(list_content)
        list_file = f.name
    try:
        _ffmpeg(
            "-f", "concat",
            "-safe", "0",
            "-i", list_file,
            "-c", "copy",
            str(out_path),
        )
    finally:
        try:
            os.unlink(list_file)
        except OSError:
            pass


def _determine_gap_ms(curr_seg: dict | None, next_seg: dict | None) -> int:
    """Calculate tight, authentic human pause duration between two dialogue turns."""
    if not curr_seg or not next_seg:
        return 180

    curr_text = curr_seg.get("text", "").strip()
    next_text = next_seg.get("text", "").strip()
    next_words = len(next_text.split())

    # 1. Quick reaction interjection ("Wait, what?", "Exactly.") -> near-instantaneous response
    if next_words <= 4:
        return 80

    # 2. Responding to a question -> alert conversational response
    if curr_text.endswith("?"):
        return 140

    # 3. Same speaker continuing thought across segments
    if curr_seg.get("speaker") == next_seg.get("speaker"):
        return 110

    # 4. Standard conversational turn
    return 180


def master(
    segment_files: list[Path],
    output_path: Path,
    assets_dir: Path | None = None,
    dialog: list[dict] | None = None,
) -> Path:
    """
    Assemble segments with tight organic pauses, room tone, broadcast EQ, and EBU R128 loudnorm.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_dir = output_path.parent / f"_mastering_tmp_{uuid.uuid4().hex[:8]}"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: Pre-process each segment (strip dead silence + apply stereo panning)
    log.info(f"Trimming padding and applying stereo staging across {len(segment_files)} segments...")
    cleaned_segs: list[Path] = []
    for i, seg_path in enumerate(segment_files):
        speaker = dialog[i].get("speaker", "Alex") if (dialog and i < len(dialog)) else "Alex"
        cleaned_path = tmp_dir / f"clean_{i:04d}.mp3"
        try:
            _clean_and_pan_segment(seg_path, cleaned_path, speaker)
            cleaned_segs.append(cleaned_path)
        except Exception as e:
            log.warning(f"Failed to clean segment {i}, using raw: {e}")
            cleaned_segs.append(seg_path)

    # Step 2: Generate dynamic room tone gaps (no digital vacuum)
    gap_cache: dict[int, Path] = {}

    def get_gap(ms: int) -> Path:
        if ms not in gap_cache:
            p = tmp_dir / f"room_{ms}ms.mp3"
            _make_room_tone(ms, p)
            gap_cache[ms] = p
        return gap_cache[ms]

    # Build ordered sequence
    ordered: list[Path] = []

    intro = (assets_dir / "intro.mp3") if assets_dir else None
    outro = (assets_dir / "outro.mp3") if assets_dir else None

    if intro and intro.exists():
        ordered.append(intro)
        ordered.append(get_gap(260))
        log.info("Intro jingle included.")

    for i, seg in enumerate(cleaned_segs):
        ordered.append(seg)
        if i < len(cleaned_segs) - 1:
            curr_d = dialog[i] if (dialog and i < len(dialog)) else None
            next_d = dialog[i + 1] if (dialog and i + 1 < len(dialog)) else None
            gap_ms = _determine_gap_ms(curr_d, next_d)
            ordered.append(get_gap(gap_ms))

    if outro and outro.exists():
        ordered.append(get_gap(260))
        ordered.append(outro)
        log.info("Outro jingle included.")

    # Step 3: Concat raw audio
    raw_concat = tmp_dir / "raw_concat.mp3"
    log.info(f"Concatenating {len(ordered)} audio elements...")
    _concat_files(ordered, raw_concat)

    # Step 4: Broadcast Warmth EQ & EBU R128 two-pass loudnorm
    log.info("Applying broadcast EQ & EBU R128 loudnorm (pass 1: measure)...")
    pass1 = _ffmpeg(
        "-i", str(raw_concat),
        "-af", f"{WARMTH_FILTER},{LOUDNORM}:print_format=json",
        "-f", "null", "-",
        check=False,
    )

    import json, re
    measured = {}
    try:
        json_matches = re.findall(r'(\{[^{}]*"input_i"[^{}]*\})', pass1.stderr, re.DOTALL)
        if json_matches:
            measured = json.loads(json_matches[-1])
    except Exception as e:
        log.warning(f"Failed to parse loudnorm pass 1 stats: {e}")

    log.info("Applying broadcast EQ & EBU R128 loudnorm (pass 2: apply)...")
    if measured.get("input_i") and measured.get("input_lra") and measured.get("input_tp"):
        loudnorm_filter = (
            f"{LOUDNORM}:"
            f"measured_I={measured['input_i']}:"
            f"measured_LRA={measured['input_lra']}:"
            f"measured_TP={measured['input_tp']}:"
            f"measured_thresh={measured.get('input_thresh', '-70')}:"
            f"offset={measured.get('target_offset', '0')}:"
            f"linear=true:print_format=none"
        )
    else:
        loudnorm_filter = LOUDNORM

    _ffmpeg(
        "-i", str(raw_concat),
        "-af", f"{WARMTH_FILTER},{loudnorm_filter}",
        "-ar", "44100",
        "-codec:a", "libmp3lame",
        "-b:a", "128k",
        str(output_path),
    )

    duration = _get_duration_seconds(output_path)
    size_mb = output_path.stat().st_size / 1024 / 1024
    log.info(f"Mastered: {output_path} | {duration:.1f}s | {size_mb:.2f} MB")

    import shutil
    shutil.rmtree(tmp_dir, ignore_errors=True)
    return output_path
